"""empty message

Revision ID: 297851713137
Revises: 72e424299015
Create Date: 2022-05-26 19:42:56.877573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297851713137'
down_revision = '72e424299015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=True),
    sa.Column('player_position', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=20), nullable=True),
    sa.Column('previous_club', sa.String(length=40), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swans')
    # ### end Alembic commands ###
