"""empty message

Revision ID: aff7e6956abe
Revises: 115386638ad5
Create Date: 2022-05-26 19:53:32.209811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff7e6956abe'
down_revision = '115386638ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swans', 'player_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('swans', 'player_position',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('swans', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('swans', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swans', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('swans', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('swans', 'player_position',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('swans', 'player_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
