"""empty message

Revision ID: d3a63190bf46
Revises: 126dc9ce273e
Create Date: 2022-05-25 12:19:52.780525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a63190bf46'
down_revision = '126dc9ce273e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'animal', ['species'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animal', type_='unique')
    # ### end Alembic commands ###
