"""empty message

Revision ID: f19d201b2ff3
Revises: aff7e6956abe
Create Date: 2022-05-26 20:52:49.224104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19d201b2ff3'
down_revision = 'aff7e6956abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swans', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swans', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
